# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: auto_green_task

on:
  #  push:
  #    branches: main
  workflow_dispatch:
  schedule:
    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时
    - cron: '0 2 1 * *'

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name:  Auto green
        run: |
          git config --local user.email "zhm35422@163.com"
          git config --local user.name "Yuuki Rito"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
